
steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.6.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd environments/platform
    terraform init
- id: 'tf validate'
  name: 'hashicorp/terraform:1.6.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    cd environments/platform
    terraform validate
- id: 'tf plan'
  name: 'hashicorp/terraform:1.6.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd environments/platform
      terraform plan
- id: 'tf apply'
  name: 'hashicorp/terraform:1.6.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd environments/platform
      terraform apply -auto-approve
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET     
